FROM jenkins/jenkins:lts

USER root

# Install Node.js 20
RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

# Install Docker CLI
RUN apt-get install -y docker.io

# Autoriser Git dans tous les répertoires (nécessaire quand root)
RUN git config --global --add safe.directory '*'
