sonar.projectKey=portfolio-react-express
sonar.projectName=Portfolio React Express - Groupe 5
sonar.projectVersion=1.0

sonar.sources=reactportfolio/src,EXPRESSJS PORTFOLIO/src,EXPRESSJS PORTFOLIO/app.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.javascript.lcov.reportPaths=EXPRESSJS PORTFOLIO/coverage/lcov.info

sonar.sourceEncoding=UTF-8

sonar.host.url=http://sonarqube:9000
