sonar.projectKey=portfolio-react-express
sonar.projectName=Portfolio React Express
sonar.projectVersion=1.0

# Sources
sonar.sources=reactportfolio/src,EXPRESSJS PORTFOLIO/src

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js

# Encodage
sonar.sourceEncoding=UTF-8

# JavaScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
